version: 2

sources:
  # - name: dagster
  #   tables:
  #     - name: augmented_plays
  #       meta:
  #         dagster:
  #           asset_key: ["raw_augmented_plays"]
            
  - name: main
    tables:
      - name: plays
        meta:
          dagster:
            asset_key: ["raw_plays"] # This metadata specifies the corresponding Dagster asset for this dbt source.

      - name: augmented_plays
        meta:
          dagster:
            asset_key: ["raw_augmented_plays"]

      - name: players
        meta:
          dagster:
            asset_key: ["raw_players"]
