version: 2

sources:
  # - name: dagster
  #   tables:
  #     - name: augmented_plays
  #       meta:
  #         dagster:
  #           asset_key: ["raw_augmented_plays"]
            
  - name: raw_data
    tables:
      - name: raw_plays
        meta:
          dagster:
            asset_key: ["raw_plays"] # This metadata specifies the corresponding Dagster asset for this dbt source.

      - name: raw_augmented_plays
        meta:
          dagster:
            asset_key: ["raw_augmented_plays"]

      - name: raw_players
        meta:
          dagster:
            asset_key: ["raw_players"]
      - name: oci_serve_speeds
        meta:
          dagster:
            asset_key: ["oci_serve_speeds"]
