services:
  r-datavolley:
    build: ./r-datavolley
    image: ethanellison/dvw-to-csv
    volumes:
      - output-files:/app/out
      - datavolley-files:/app/dvw
  
  dagster-datavolley:
    build: ./dagster_datavolley
    image: ethanellison/dagster-datavolley
    volumes:
      - datavolley-files:/app/dvw
      - output-files:/app/out
      # - ./dagster_datavolley:/app
    ports:
      - "3000:3000"
    # depends_on:
    #   r-datavolley:
    #     condition: service_completed_successfully
    develop:
      watch:
        - action: sync
          path: ./dagster_datavolley
          target: /app
          ignore:
            - ./dagster_datavolley/Dockerfile
    env_file:
      - ./.env
  
  file-browser:
    build: ./files
    image: ethanellison/file-browser
    volumes:
      - datavolley-files:/files/datavolley
      - output-files:/files/out
    ports:
      - "8080:8080"


volumes:
  datavolley-files:
  output-files:
  
