version: 2

sources:
  - name: raw
    database: datavolley
    schema: datavolley.rseq
    tables:
      - name: "output.json"
      - name: "plays.gz.parquet"
      - name: "augmented_plays.gz.parquet"
      - name: "players.gz.parquet"
      # - name: oci_serve_speeds
  - name: dim
    schema: datavolley.dim
    tables:
      - name: dim_attack_codes
