version: 2

sources:
  - name: raw
    schema: datavolley.raw
    tables:
      - name: raw_matches
      - name: raw_plays
      - name: raw_augmented_plays
      - name: raw_players
      - name: oci_serve_speeds
  - name: dim
    schema: datavolley.dim
    tables:
      - name: dim_attack_codes
