services:
  # notebook:
  #   build: ./notebook
  #   # image: ethanellison/dvw-to-csv
  #   container_name: notebook
  #   networks:
  #     iceberg_net:
  #   volumes:
  #     - ./notebook/ingest:/home/jovyan/work
  #     - ./notebook/.jupyter:/home/jovyan/.jupyter
  #   user: root
  #   environment:
  #     - CHOWN_EXTRA=/home/jovyan/
  #     - CHOWN_EXTRA_OPTS=-R
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
  #     - PYICEBERG_CATALOG__REST__URI=http://iceberg-rest:8181/
  #     - PYICEBERG_CATALOG__REST__S3__ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - PYICEBERG_CATALOG__REST__S3__SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - PYICEBERG_CATALOG__REST__S3__ENDPOINT=${CATALOG_S3_ENDPOINT}
  #   ports:
  #     - "8888:8888"
  
  # dagster-datavolley:
  #   build: ./dagster_datavolley
  #   image: ethanellison/dagster-datavolley
  #   container_name: dagster
  #   networks:
  #     iceberg_net:
  #   volumes:
  #     - /mnt/smbshare/eellison/rseq 24-25:/app/dvw
  #     # - output-files:/app/out
  #     - /mnt/smbshare/eellison/rseq 24-25/out:/app/out
  #     # - ./dagster_datavolley:/app
  #   ports:
  #     - "3000:3000"

  #   # develop:
  #   #   watch:
  #   #     - action: sync
  #   #       path: ./dagster_datavolley
  #   #       target: /app
  #   #       ignore:
  #   #         - ./dagster_datavolley/Dockerfile
  #   # env_file:
  #   #   - ./.env

  nessie:
    image: quay.io/projectnessie/nessie:latest
    container_name: nessie
    networks:
      iceberg_net:
    ports:
      - 19120:19120

  rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - CATALOG_WAREHOUSE=${CATALOG_WAREHOUSE}
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=${CATALOG_S3_ENDPOINT}
# volumes:
#   postgres-data:
  # output-files:
  
  dremio-oss:
    container_name: dremio
    image: dremio/dremio-oss
    networks:
      iceberg_net:
    # network_mode: service:ts-dremio
    user: root
    volumes:
      - ./conf/core-site.xml:/opt/dremio/conf/core-site.xml
      - ./conf/dremio.conf:/opt/dremio/conf/dremio.conf
      - dremio-data:/opt/dremio/data
    ports:
      - 9047:9047
      - 31010:31010
      - 45678:45678
      - 32010:32010

networks:
  iceberg_net:

volumes:
  dremio-data:
