dbt_datavolley:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: datavolley.duckdb
      threads: 4
      schema: dbt_schema
      extensions:
        - httpfs
        - parquet
        - json
